### PR TITLE
[8.0-development][babycare_product_brand] update of the complete module

### PR DESCRIPTION
**Pull request by wytzejan**
- new models and views are added for different attributes
- translation files for Dutch and German are added
- new menu for manage and sync all attributes in the model

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
You exploded each option into a separate model and views. This does not scale well.

I would create a generic system with a product.option model. A product would have a list of options. Each option would have a code (Product Brand, Product Color, etc). A code would be a distinct model product.option.code which would have a type (selection, text, numeric) and optionally a set of possible values. A function field would calculate the representation of the product option. You can use this representation to sync to Magento. A product would have any number of product option (but only one per code).

This should not be too hard to do.

An additional benefit is that you could easily phase out codes by setting them to inactive, so that they cannot be assigned anymore to new products.

**Comment by StefanRijnhart** [comment]
Merging as per comments on the task in our Odoo instance.

**Review by StefanRijnhart — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Oh, cannot merge (no write access to this repository)

**Comment by wytzejan** [comment]
Thanks for your comments.
I made you collaborator on this repo. It should work now.

**Comment by wytzejan** [comment]
I close this PR.
I changed the complete module based on your comments in our Odoo instance.
New PR will be placed soon.

**Pull request closed without merging**
