### PR TITLE
Tasks/2800/expected date on pickings

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by wytzejan — CHANGES_REQUESTED** [review]
- The scheduled date (max_date) on the stock picking form is a read-only field. Is it possible to make this is an editable field? (Sometimes we've 80+ product lines on our picking list and we'd like to change the scheduled date (max_date) in this case.)

- Behind the scheduled date (max_date) there is a time indication (both on the form as in the product listing). This time indication may be removed so that we only see the date.

**Comment by StefanRijnhart** [comment]
Hi Wytzejan,

like the minimum date, the maximum date is a computed field based on the values from the stock moves, so it cannot be changed. We'd have to design a workaround if you want that. I can render the datetime as a date field though.

**Comment by wytzejan** [comment]
@StefanRijnhart Can you have a look at the current set-up of min_date in the production environment? This field is both editable **and** computed. In case the planned date changes on the form the planned date/min_date of all product lines will be the same as this planned date on the form. After that the min_date of individual lines in de stock picking list can be individual edited. On save the min_date on the form displays the highest min_date of all product lines.
It looks like this is inconvenient for a computed field but for us it's very handy: imagine a stock picking list of 80+ products (we do have this a lot). In case the planned date for every product on the list changes to the same product, but the planned date on the form is not editable, we've to change every planned date of the product individual. This is very inefficient.
The above (planned date both computed and editable) should be possible I think.

**Comment by StefanRijnhart** [comment]
Thanks for noting that the min_date can be overwritten! When it is, it overwrites the expected dates of the stock moves on the picking. I can apply the same trick to the max_date if you agree to the consequence (losing the original dates on the stock moves). Please let me know.

**Comment by wytzejan** [comment]
@StefanRijnhart Yes, please go ahead and apply the same trick to max_date. We agree with the consequences. We'll change the max_date on the individual lines if necessary.

**Comment by StefanRijnhart** [comment]
OK, I'll do that over the next couple of days.

**Comment by StefanRijnhart** [comment]
There you go!

**Comment by StefanRijnhart** [comment]
Latest version of this PR installed on the test instance.

**Review by wytzejan — APPROVED** [review]

**Comment by wytzejan** [comment]
@StefanRijnhart Exactly as expected! Thanks :)

**Pull request merged**
